version: '3.7'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: mir32/foodgram_backend:latest
    restart: always
    environment:
      - DB_HOST=db
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file: .env

  frontend:
    image: mir32/foodgram_frontend:latest
    volumes:
      - frontend_value:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - frontend_value:/usr/share/nginx/html/

    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_value:
  db_value: